'use client';

import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Check, Code2, Command, Layers3, Plus, Send, Sparkles, X } from 'lucide-react';
import SiteHeader from '../components/SiteHeader';
import SiteFooter from '../components/SiteFooter';
import LogoMarquee from '../components/LogoMarquee';

const A = '/assets/';
const projects = [
  { name: 'ProRota', type: 'Nexverse product · Workforce management', image: `${A}portfolio/prorota-impact.jpg`, number: '01', description: 'A workforce management platform, shown across desktop and mobile.' },
  { name: 'AB3 Medical', type: 'Selected client work', image: `${A}portfolio/ab3-clinician-dashboard.webp`, number: '02', description: 'A digital product from the Nexverse project archive.' },
  { name: 'Ahlmark', type: 'Selected client work', image: `${A}portfolio/ahlmark-featured-hero.jpg`, number: '03', description: 'A digital project from the Nexverse archive.' },
];
const homeClients = [
  ['ab3-medical.svg','AB3 Medical'],['ahlmark.svg','Ahlmark'],['airco.svg','Airco'],['duralean.svg','Duralean'],
  ['lambson.svg','Lambson'],['limitless.svg','Limitless'],['odlings.svg','Odlings'],['virtually-golf.svg','Virtually Golf'],['westwood.svg','Westwood'],['ymca.svg','YMCA'],
];
const teamPreview = [['usman-devops-lead.png','Usman'],['haider.png','Haider'],['abdullah.png','Abdullah']];
const services = [
  { n: '01', title: 'Bespoke software', desc: 'Purpose-built software shaped around the way your business works.', icon: Code2, tags: ['Custom platforms', 'Business systems'] },
  { n: '02', title: 'Websites & CMS', desc: 'Flexible WordPress and headless experiences, designed to evolve.', icon: Layers3, tags: ['WordPress', 'Headless CMS'] },
  { n: '03', title: 'E-commerce', desc: 'Thoughtful online stores that make every step feel effortless.', icon: Command, tags: ['Online stores', 'Integrations'] },
  { n: '04', title: 'Apps & automation', desc: 'Connected digital tools that simplify the everyday and scale with you.', icon: Sparkles, tags: ['Web apps', 'Workflows'] },
];

function CoreCanvas({ scrollPhase }) {
  const host = useRef(null);
  const phaseRef = useRef(scrollPhase);
  useEffect(() => { phaseRef.current = scrollPhase; }, [scrollPhase]);
  useEffect(() => {
    if (!host.current) return;
    const el = host.current;
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(34, el.clientWidth / el.clientHeight, 0.1, 100);
    camera.position.set(0, 0, 8);
    let renderer;
    try { renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true, powerPreference: 'high-performance' }); }
    catch { el.classList.add('no-webgl'); return; }
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 1.7));
    renderer.setSize(el.clientWidth, el.clientHeight);
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    el.appendChild(renderer.domElement);
    const core = new THREE.Group(); scene.add(core);
    const markScale=.023; const emblemParts=[];
    const addMarkPart=(points,cx,cy)=>{const shape=new THREE.Shape();points.forEach(([x,y],i)=>{const px=(x-96)*markScale,py=(96-y)*markScale;if(i===0)shape.moveTo(px,py);else shape.lineTo(px,py)});shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:.24,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.035,bevelThickness:.035});geometry.center();const material=new THREE.MeshPhysicalMaterial({color:'#468EEF',metalness:.12,roughness:.42,clearcoat:.65,emissive:'#468EEF',emissiveIntensity:.2});const part=new THREE.Mesh(geometry,material);part.position.set((cx-96)*markScale,(96-cy)*markScale,0);part.userData.baseX=part.position.x;part.userData.baseY=part.position.y;const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geometry,20),new THREE.LineBasicMaterial({color:'#B5D6FF',transparent:true,opacity:.72}));part.add(edge);part.userData.edge=edge;core.add(part);emblemParts.push(part)};
    // The signature mark is rebuilt from crisp vector polygons: open chevron and its two forward strokes.
    addMarkPart([[48,44],[72,44],[107,96],[72,148],[48,148],[83,96]],70,96);
    addMarkPart([[102,44],[144,44],[117,84],[102,66]],116,60);
    addMarkPart([[102,122],[127,122],[144,148],[117,148],[99,127]],118,137);
    const ringMat = new THREE.MeshBasicMaterial({ color: '#468EEF', transparent: true, opacity: .46 });
    const ring = new THREE.Mesh(new THREE.TorusGeometry(2.24, .008, 8, 180), ringMat); ring.rotation.x = Math.PI * .48; ring.rotation.y = .3; core.add(ring);
    const ring2 = new THREE.Mesh(new THREE.TorusGeometry(2.46, .005, 8, 180), new THREE.MeshBasicMaterial({ color: '#EEF7FF', transparent: true, opacity: .16 })); ring2.rotation.x = .9; ring2.rotation.y = -.6; core.add(ring2);
    const satelliteMaterial = new THREE.MeshStandardMaterial({ color: '#EEF7FF', emissive: '#468EEF', emissiveIntensity: .48, metalness: .35, roughness: .25 });
    const satellites = Array.from({length:6},()=>{const node=new THREE.Mesh(new THREE.OctahedronGeometry(.085,0),satelliteMaterial);scene.add(node);return node});
    const pipeGeometry=new THREE.BufferGeometry(); const pipePositions=new Float32Array(satellites.length*6); pipeGeometry.setAttribute('position',new THREE.BufferAttribute(pipePositions,3));
    const pipes=new THREE.LineSegments(pipeGeometry,new THREE.LineBasicMaterial({color:'#468EEF',transparent:true,opacity:.5}));scene.add(pipes);
    const imageCards=[]; const textureLoader=new THREE.TextureLoader();
    projects.forEach((project,i)=>{const texture=textureLoader.load(project.image);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshBasicMaterial({map:texture,transparent:true,opacity:0,side:THREE.DoubleSide});const card=new THREE.Mesh(new THREE.PlaneGeometry(1.95,1.28),material);card.position.set((i-1)*2.18, i===1?.05:.18, 1.18);card.userData.baseX=card.position.x;card.userData.baseY=card.position.y;scene.add(card);imageCards.push(card)});
    const count = window.innerWidth < 720 ? 320 : 760;
    const positions = new Float32Array(count * 3); const sizes = new Float32Array(count);
    for (let i=0;i<count;i++){ const r=2.5+Math.random()*4.3, theta=Math.random()*Math.PI*2, phi=Math.acos(2*Math.random()-1); positions[i*3]=r*Math.sin(phi)*Math.cos(theta); positions[i*3+1]=r*Math.sin(phi)*Math.sin(theta); positions[i*3+2]=r*Math.cos(phi); sizes[i]=Math.random(); }
    const pg = new THREE.BufferGeometry(); pg.setAttribute('position',new THREE.BufferAttribute(positions,3));
    const particles = new THREE.Points(pg,new THREE.PointsMaterial({ color:'#78b6ff', size:.018, transparent:true, opacity:.55, sizeAttenuation:true })); scene.add(particles);
    scene.add(new THREE.AmbientLight('#EEF7FF', 1.25)); const key=new THREE.PointLight('#468EEF',24,20); key.position.set(3,2,5); scene.add(key); const cyan=new THREE.PointLight('#FFFFFF',9,12); cyan.position.set(-3,-2,1); scene.add(cyan);
    let raf; let pointerX=0, pointerY=0; const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const onMove=e=>{pointerX=(e.clientX/window.innerWidth-.5)*.28;pointerY=(e.clientY/window.innerHeight-.5)*.2}; window.addEventListener('pointermove',onMove,{passive:true});
    const resize=()=>{if(!el.clientWidth)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)}; window.addEventListener('resize',resize);
    let t=0; const render=()=>{raf=requestAnimationFrame(render);t+=reduced?.002:.006;const p=reduced?0:phaseRef.current?.current?.value||0;
      core.rotation.y=Math.sin(t*.35)*.06+Math.sin(p*Math.PI)*.72;core.rotation.x=Math.sin(t*.7)*.08+pointerY+(p-.5)*.12;core.rotation.z=Math.sin(t*.42)*.05+pointerX;
      ring.rotation.z=.3+Math.sin(t*.25)*.12+p*Math.PI*.5;ring2.rotation.z=-.6-p*Math.PI*.72;particles.rotation.y+=.0002;
      const partsOpen=Math.max(0,Math.min(1,(p-.23)*3.1));emblemParts.forEach((part,i)=>{const dir=i===0?-1:1;part.position.x=part.userData.baseX+dir*partsOpen*(i===0?.28:.2);part.position.y=part.userData.baseY+(i===1?partsOpen*.2:i===2?-partsOpen*.2:0);part.rotation.y=dir*partsOpen*.13;});
      camera.position.z=7.3+.52*Math.sin(p*Math.PI*2)+p*.35;camera.position.x+=(pointerX*1.1+Math.sin(p*Math.PI*2)*.35-camera.position.x)*.025;
      const constellation=Math.max(0,Math.min(1,(p-.2)*3.2));
      satellites.forEach((node,i)=>{const a=(i/satellites.length)*Math.PI*2+t*.16;const radius=2.05+constellation*.9;const x=Math.cos(a)*radius;const y=Math.sin(a)*radius*.72;node.position.set(x,y,Math.sin(a*2+t)*.72);node.rotation.x=t*.42+i;node.rotation.y=-t*.35;const attr=pipeGeometry.attributes.position;attr.setXYZ(i*2,Math.cos(a)*1.5,Math.sin(a)*1.05,0);attr.setXYZ(i*2+1,x,y,node.position.z);});
      pipeGeometry.attributes.position.needsUpdate=true;const cardReveal=Math.max(0,Math.min(1,(p-.68)*3.2));imageCards.forEach((card,i)=>{const a=cardReveal;card.material.opacity=a;card.position.x=card.userData.baseX*(.15+.85*a);card.position.y=card.userData.baseY*a+Math.sin(t+i)*.035;card.scale.setScalar(.78+.22*a);card.rotation.y=(1-a)*(i-1)*.55;});
      camera.lookAt(0,0,0);renderer.render(scene,camera)}; render();
    return()=>{cancelAnimationFrame(raf);window.removeEventListener('pointermove',onMove);window.removeEventListener('resize',resize);renderer.dispose();pg.dispose();pipeGeometry.dispose();satelliteMaterial.dispose();emblemParts.forEach(part=>{part.geometry.dispose();part.material.dispose();part.userData.edge.geometry.dispose();part.userData.edge.material.dispose()});satellites.forEach(n=>{n.geometry.dispose();scene.remove(n)});imageCards.forEach(card=>{card.geometry.dispose();card.material.map?.dispose();card.material.dispose();scene.remove(card)});[ring.geometry,ring.material,ring2.geometry,ring2.material,particles.material].forEach(v=>v.dispose());el.removeChild(renderer.domElement)};
  },[]);
  return <div className="core-canvas" ref={host} aria-hidden="true"><div className="canvas-fallback"><div className="fallback-core"/></div></div>;
}

export default function Home(){
  const [stage,setStage]=useState(0); const scrollPhase=useRef({value:0}); const [drawer,setDrawer]=useState(false); const [active,setActive]=useState(null); const [budget,setBudget]=useState(2); const [sent,setSent]=useState(false);
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger); const els=gsap.utils.toArray('[data-reveal]'); els.forEach(el=>gsap.fromTo(el,{y:34,opacity:0},{y:0,opacity:1,duration:.85,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));
    const journey=gsap.timeline({scrollTrigger:{trigger:'.journey',start:'top top',end:'bottom bottom',scrub:1}});journey.to(scrollPhase.current,{value:1,duration:1,ease:'none',onUpdate(){const p=this.targets()[0].value;const next=Math.min(3,Math.floor(p*4));setStage(current=>current===next?current:next)}});
    return()=>{journey.scrollTrigger?.kill();journey.kill();ScrollTrigger.getAll().forEach(t=>t.kill())};},[]);
  useEffect(()=>{document.body.style.overflow=drawer||active?'hidden':'';return()=>{document.body.style.overflow=''}},[drawer,active]);
  const close=()=>{setDrawer(false);setActive(null)};
  const submit=e=>{e.preventDefault();setSent(true)};
  return <main>
    <SiteHeader onContact={()=>setDrawer(true)}/>
    <section className="hero" id="home"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> DIGITAL ENGINEERING STUDIO <span className="eyebrow-line"/> EST. FOR WHAT’S NEXT</div><h1><span>Architects</span><span>of the <i>digital</i></span><span className="future">future<span className="title-period">.</span></span></h1><div className="hero-bottom"><p>We turn ambitious ideas into <em>digital reality.</em><br/>Strategy, design and engineering for what comes next.</p><a href="#journey" className="hero-scroll"><span>SCROLL TO EXPLORE</span><ArrowDownRight size={19}/></a></div></div><div className="hero-index">01 <span>/</span> 04</div><div className="hero-coordinates">51°30′26.4″N<br/>00°07′39.6″W</div><div className="orb-halo"/><div className="hero-mark">N<span>×</span>V</div></section>
    <section className="journey" id="journey"><div className="journey-sticky"><div className="journey-grid"/><CoreCanvas stage={stage} scrollPhase={scrollPhase}/><div className="journey-top"><span>THE NEXVERSE METHOD</span><span>01 — 04</span></div><div className="journey-caption"><span className="caption-dot"/> DIGITAL SYSTEM / NV–01 <span className="caption-rule"/> LIVE ENGINE</div><div className="journey-copy"><article className={stage===0?'selected':''} data-stage="0"><span className="step-num">01 / ARCHITECTURE</span><h2>Built around<br/>your <i>ambition.</i></h2><p>Bespoke software and cloud-ready foundations. Technology that fits your business today—and gives it room to grow.</p><a href="#services" className="text-link">Explore our services <ArrowUpRight size={15}/></a></article><article className={stage===1?'selected':''} data-stage="1"><span className="step-num">02 / ENGINEERING</span><h2>Fluid by<br/><i>design.</i></h2><p>Connected web and app experiences, engineered to feel effortless and work beautifully together.</p><a href="#technology" className="text-link">Meet the toolkit <ArrowUpRight size={15}/></a></article><article className={stage===2?'selected':''} data-stage="2"><span className="step-num">03 / INTELLIGENCE</span><h2>More flow.<br/><i>Less friction.</i></h2><p>Commerce and workflows designed to make complex journeys feel simple—from first click to fulfilled order.</p><a href="#services" className="text-link">See what we solve <ArrowUpRight size={15}/></a></article><article className={stage===3?'selected':''} data-stage="3"><span className="step-num">04 / SELECTED WORK</span><h2>Made for<br/><i>what’s next.</i></h2><p>Selected digital work across creative, product and emerging technology.</p><a href="#work" className="text-link">Discover the work <ArrowUpRight size={15}/></a></article></div><div className="journey-progress"><span className={stage===0?'on':''}/><span className={stage===1?'on':''}/><span className={stage===2?'on':''}/><span className={stage===3?'on':''}/></div></div><div className="journey-scroll" aria-hidden="true"><div data-stage="0"/><div data-stage="1"/><div data-stage="2"/><div data-stage="3"/></div></section>
    <section className="intro section-pad" id="about" data-reveal><div className="section-kicker"><span>01 — THE POINT OF VIEW</span><span>IDEAS, ENGINEERED.</span></div><div className="intro-layout"><div className="intro-head"><span className="small-cross">✳</span><h2>Digital should<br/>move you <i>forward.</i></h2></div><div className="intro-body"><p>At Nexverse, we are architects of the digital future. We bring ideas to life through bespoke software, web and app development, custom WordPress solutions, and e-commerce innovation.</p><p>Good technology does more than work. It opens new possibilities for the people and businesses using it.</p><a className="text-link" href="#services">How we can help <ArrowUpRight size={15}/></a></div></div><div className="intro-meta"><span>STRATEGY <b>+</b> DESIGN <b>+</b> ENGINEERING</span><span>BUILT TO MOVE WITH YOU <ArrowRight size={14}/></span></div></section>
    <section className="featured-product section-pad" id="product"><div className="section-kicker" data-reveal><span>02 — NEXVERSE PRODUCT</span><span>INTRODUCING PROROTA.</span></div><div className="featured-product-layout"><div className="featured-product-copy" data-reveal><span className="product-label"><span className="status-dot"/> WORKFORCE MANAGEMENT</span><h2>ProRota<span>.</span><br/><i>Work, in sync.</i></h2><p>Scheduling, teams and day-to-day operations brought into one clear workspace. Meet the product we’re building at Nexverse.</p><a href="/products" className="text-link">Explore ProRota <ArrowUpRight size={15}/></a></div><a href="/products" className="featured-product-image" data-reveal><img src={`${A}portfolio/prorota-impact.jpg`} alt="ProRota workforce management dashboard displayed on desktop and mobile"/><span className="product-image-label">PROROTA / PRODUCT VIEW <ArrowUpRight size={14}/></span></a></div></section>
    <section className="services section-pad" id="services"><div className="section-kicker" data-reveal><span>03 — CAPABILITIES</span><span>THOUGHTFULLY BUILT. PURPOSEFULLY MADE.</span></div><div className="services-heading" data-reveal><h2>Complexity, <i>made simple.</i></h2><p>From the first sketch to the final line of code, we bring the right people and technology to the problem.</p></div><div className="service-grid">{services.map(({n,title,desc,icon:Icon,tags})=><article className="service-card" key={n} data-reveal><div className="service-top"><span>{n}</span><Icon size={20}/></div><h3>{title}</h3><p>{desc}</p><div className="service-tags">{tags.map(t=><span key={t}>{t}</span>)}</div><div className="service-plus"><Plus size={14}/></div></article>)}</div><a href="/services" className="text-link service-more">Explore services &amp; industries <ArrowUpRight size={15}/></a></section>
    <section className="work section-pad" id="work"><div className="section-kicker" data-reveal><span>03 — SELECTED WORK</span><span>PRODUCTS &amp; PARTNERSHIPS.</span></div><div className="work-heading" data-reveal><h2>Made for<br/><i>what’s next.</i></h2><p>From our own product to work made alongside ambitious teams.</p><span className="work-count">03 <i>FEATURES</i></span></div><div className="project-grid">{projects.map((p,i)=><button className={`project-card project-${i+1}`} key={p.name} onClick={()=>setActive(p)} data-reveal><div className="project-visual"><img src={p.image} alt={`${p.name} project`} loading="lazy"/><span className="project-overlay"/><span className="project-open"><ArrowUpRight size={18}/></span><span className="project-number">{p.number} / 03</span></div><div className="project-info"><div><h3>{p.name}<span>.</span></h3><p>{p.type}</p></div><ArrowUpRight className="project-arrow" size={19}/></div></button>)}</div><div className="work-foot"><a href="/work">VIEW CLIENTS &amp; PROJECTS <ArrowUpRight size={14}/></a><a href="/products">DISCOVER PROROTA <ArrowUpRight size={14}/></a></div></section>
    <section className="client-strip section-pad"><div className="section-kicker" data-reveal><span>04 — IN GOOD COMPANY</span><span>ORGANIZATIONS IN OUR NETWORK.</span></div><LogoMarquee logos={homeClients}/><a className="text-link" href="/work">See clients &amp; selected work <ArrowUpRight size={15}/></a></section>
    <section className="technology section-pad" id="technology"><div className="section-kicker" data-reveal><span>05 — THE TOOLKIT</span><span>RIGHT TOOL. RIGHT REASON.</span></div><div className="tech-layout"><div className="tech-copy" data-reveal><span className="tech-orbit"><span/><span/><span/><i>NV</i></span><h2>Technology is<br/>the <i>material.</i></h2><p>We choose the tools that make your idea work—then connect them into something greater than the sum of its parts.</p></div><div className="tech-board" data-reveal><div className="tech-board-head"><span>SELECTED TECHNOLOGIES</span><span>01 — 03</span></div><div className="tech-items">{[['figma.png','Figma','DESIGN'],['nodejs.png','Node.js','RUNTIME'],['wordpress.png','WordPress','CMS']].map(([src,name,kind],i)=><div className="tech-item" key={name}><div className="tech-icon"><img src={A+'tech/'+src} alt=""/></div><div className="tech-name"><b>{name}</b><span>{kind}</span></div><span className="tech-index">0{i+1}</span><ArrowUpRight size={14}/></div>)}</div><div className="tech-board-foot"><span>BUILT FOR YOUR CONTEXT</span><span>ALWAYS EVOLVING <span className="status-dot"/></span></div></div></div></section>
    <section className="solutions section-pad"><div className="section-kicker" data-reveal><span>05 — SYSTEMS IN MOTION</span><span>A SNEAK PEEK UNDER THE HOOD.</span></div><div className="solutions-top" data-reveal><h2>Small steps.<br/><i>Better systems.</i></h2><p>Our digital solutions connect the moving parts—giving teams a little more time for what matters.</p></div><div className="solutions-grid">{[['forms-1.png','01 / CAPTURE','Make every enquiry count'],['automation-1.png','02 / CONNECT','Keep the work moving'],['invoicing-1.png','03 / COMPLETE','Close the loop, beautifully']].map(([src,n,title])=><article className="solution-card" key={src} data-reveal><div className="solution-image"><img src={A+'solutions/'+src} alt={title} loading="lazy"/></div><div className="solution-meta"><span>{n}</span><ArrowUpRight size={14}/></div><h3>{title}</h3></article>)}</div></section>
    <section className="team-preview section-pad"><div className="section-kicker" data-reveal><span>06 — THE PEOPLE</span><span>A CLOSE-KNIT TEAM, BUILT AROUND THE WORK.</span></div><div className="team-preview-layout"><div><h2>People make<br/><i>the difference.</i></h2><a href="/about" className="text-link">Meet the team <ArrowUpRight size={15}/></a></div><div className="team-preview-people">{teamPreview.map(([photo,name])=><a href="/about" className="team-preview-card" key={name}><img src={`${A}team/${photo}`} alt={name} loading="lazy"/><span>{name}</span></a>)}</div></div></section>
    <section className="estimator section-pad" id="contact"><div className="section-kicker" data-reveal><span>07 — YOUR NEXT MOVE</span><span>LET’S FIND A WAY FORWARD.</span></div><div className="estimate-layout"><div className="estimate-copy" data-reveal><span className="estimate-tag"><span className="status-dot"/> PROJECT PLANNER</span><h2>Big idea.<br/><i>Clear next step.</i></h2><p>Tell us a little about what you’re building. We’ll help you shape the scope and find a starting point.</p><div className="estimate-email"><span>OR WRITE TO US DIRECTLY</span><a href="mailto:contact@nexverse.co.uk">contact@nexverse.co.uk <ArrowUpRight size={15}/></a></div></div><div className="estimate-panel" data-reveal><div className="estimate-panel-head"><span>01 / PROJECT SCOPE</span><span>~ 1 MIN</span></div><label htmlFor="scope">What are you looking to build?</label><select id="scope"><option>A website or digital experience</option><option>Custom software or platform</option><option>E-commerce store</option><option>App or workflow automation</option><option>Something else</option></select><label>Estimated project investment</label><div className="budget-options">{['Under £5k','£5k – £15k','£15k – £30k','£30k+'].map((b,i)=><button onClick={()=>setBudget(i)} className={budget===i?'chosen':''} key={b}>{budget===i&&<Check size={13}/>} {b}</button>)}</div><button className="estimate-submit" onClick={()=>setDrawer(true)}>Continue your enquiry <ArrowRight size={16}/></button><span className="estimate-privacy">NO PRESSURE. JUST A GOOD CONVERSATION.</span></div></div></section>
    <SiteFooter/>
    {(drawer||active)&&<div className="modal-scrim" onClick={close}><button className="modal-close" onClick={close} aria-label="Close"><X size={20}/></button>{drawer?<aside className="contact-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-top"><span>PROJECT ENQUIRY / 2026</span><span className="status-dot"/></div>{sent?<div className="sent-state"><span className="sent-check"><Check size={22}/></span><h2>Thanks for<br/><i>reaching out.</i></h2><p>Your enquiry is ready to start a conversation. We’ll be in touch soon.</p><button onClick={()=>{setDrawer(false);setSent(false)}} className="text-link">Back to the site <ArrowRight size={14}/></button></div>:<><h2>Every great thing<br/>starts <i>somewhere.</i></h2><p className="drawer-intro">Give us the outline. We’ll help with the details.</p><form onSubmit={submit}><label htmlFor="name">YOUR NAME</label><input required id="name" placeholder="How should we address you?"/><label htmlFor="email">EMAIL ADDRESS</label><input required type="email" id="email" placeholder="you@company.com"/><label htmlFor="message">A LITTLE ABOUT THE PROJECT</label><textarea required id="message" rows="3" placeholder="The idea, the challenge, the ambition…"/><button className="send-button" type="submit">Send enquiry <Send size={16}/></button></form><div className="drawer-footer">PREFER EMAIL? <a href="mailto:contact@nexverse.co.uk">CONTACT@NEXVERSE.CO.UK</a></div></>}</aside>:<div className="project-modal" onClick={e=>e.stopPropagation()}><img src={active.image} alt={`${active.name} project`} /><div className="project-modal-copy"><span>{active.number} / SELECTED WORK</span><h2>{active.name}<i>.</i></h2><p>{active.description}</p><span className="project-modal-type">{active.type.toUpperCase()}</span></div></div>}</div>}
  </main>
}
