import SiteHeader from '../../components/SiteHeader';
import SiteFooter from '../../components/SiteFooter';
import { ArrowDownRight, ArrowUpRight, Check, MapPin, Users, CalendarDays, ShieldCheck } from 'lucide-react';

const productDetails = [
  { icon: CalendarDays, title: 'Rota planning', text: 'Build and review team schedules in one workspace.' },
  { icon: Users, title: 'People & teams', text: 'Keep workforce information close to day-to-day operations.' },
  { icon: MapPin, title: 'Attendance', text: 'Support mobile check-in and location-aware workflows.' },
  { icon: ShieldCheck, title: 'Compliance', text: 'Bring operational records and compliance checks together.' },
];

export const metadata = { title: 'ProRota — Nexverse', description: 'Meet ProRota, a Nexverse workforce management product.' };

export default function ProductsPage(){return <main className="inner-page product-page"><SiteHeader/><section className="inner-hero product-hero"><div className="inner-eyebrow">NEXVERSE PRODUCT / 01</div><div className="product-hero-grid"><div><span className="product-label"><span className="status-dot"/> WORKFORCE MANAGEMENT</span><h1>ProRota<span>.</span><br/><i>Operations,<br/>in sync.</i></h1><p>Scheduling, teams and daily operations, brought into one clear workspace. ProRota is a workforce management product from Nexverse.</p><div className="inner-actions"><a className="primary-link" href="/#contact">Talk to our team <ArrowUpRight size={16}/></a><a className="quiet-link" href="#platform">Explore the platform <ArrowDownRight size={16}/></a></div></div><div className="product-display"><div className="display-glow"/><div className="display-frame"><img src="/assets/portfolio/prorota-impact.jpg" alt="ProRota workforce management interface on a laptop and mobile device"/></div><div className="display-label">PROROTA / PRODUCT VIEW <span>01—04</span></div><div className="product-orbit orbit-one"/><div className="product-orbit orbit-two"/></div></div></section><section className="product-intro section-pad" id="platform"><div className="section-kicker"><span>01 — THE PLATFORM</span><span>MADE FOR THE MOVING PARTS.</span></div><div className="product-intro-grid"><h2>One workspace.<br/><i>More clarity.</i></h2><p>ProRota brings schedules, people and operational information into a shared view—designed for teams that need to stay coordinated across sites and shifts.</p></div><div className="product-capabilities">{productDetails.map(({icon:Icon,title,text},i)=><article className="product-capability" key={title}><span>0{i+1}</span><Icon size={21}/><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="product-screen-section"><div className="product-screen-copy"><span className="inner-eyebrow">THE WORK, AT A GLANCE</span><h2>See the shape<br/>of the week.</h2><p>Schedules and team activity sit together, so the moving parts are easier to follow.</p></div><div className="product-screen-card"><img src="/assets/products/prorota2.png" alt="ProRota platform schedule interface" loading="lazy"/></div></section><section className="product-cta section-pad"><span className="inner-eyebrow">A NEXVERSE PRODUCT</span><h2>Build a better<br/><i>working rhythm.</i></h2><a className="primary-link" href="/#contact">Ask us about ProRota <ArrowUpRight size={16}/></a></section><SiteFooter/></main>}
